### ISSUE TITLE
batoto.net -> bato.to

### ISSUE THREAD

**Issue by Gitii** [DeepBhattacharya/manga-downloader#6]
Hi,

the new url is http://bato.to/... (which wont be accepted by the script)
the old http://batoto.net/... will be redirected.

Its easy to "fix" the manga url manually but it is easier (for users) to extend the check in the script.

Greetings

**Comment by deepbhattacharya** [comment]
Hi - the script accepts bato.to (note URL_TYPES); however the README hasn't been updated in a long while...
